### ISSUE TITLE
Using @property for setters and getters

### ISSUE THREAD

**Issue by bocklund** [atztogo/phonopy#39]
Hello!

I've noticed that many places in the code use a style like `get_my_property(self)` such as in Phonopy/qha/eos.py where there is 

```
def get_volume(self):
    if self._parameters is None:
        return None
    else:
        return self._parameters[3]
```

Python was designed with this kind of application in mind and provide the `property()` method as a replacement for this syntax.

```
@property
def volume(self):
        return self._parameters[3]
```

That way you can access the volume by doing

```
e = EOSFit(...)
e.run(...)
e.volume
# instead of:
# e.get_volume()
```

By the way, both of these codes are 'broken' in the sense that if you don't use `EOSFit.run()` they will not return None, but will instead give you an attribute error. 

I would be happy to make these changes throughout the codebase and submit a pull request, but I wanted to check that you welcome such changes into the API.

**Comment by atztogo** [comment]
You are correct. Your pull request is of course welcome. I know I'm not a good python programmer, but I can guess it's the correct direction if we want phonopy to be more useful and to live longer.
My concern is the backward compatibility. I don't know how many people rely on phonopy's API. But probably it would be better to keep current getter methods for a while.

**Comment by jochym** [comment]
Property pattern seems to be more pythonic, but the setters/getters pattern is not wrong as well. I think it is mostly a matter of taste. You do not need to break the API, you can gave both and slowly depreciate the one you intend to keep. I personally like the attributes, but that is just my opinion. If you like to look for clean-ups in the code @bocklund, it may be useful to review the list generated by quantifiedcode (https://www.quantifiedcode.com/app/project/gh:jochym:phonopy). Not everything there is worth correcting but some points are good ideas.

**Comment by bocklund** [comment]
@jochym I've never seen this tool before, it looks useful for my projects. I'll take a look at some things that I may be able to do for phonopy.

**Comment by ajjackson** [comment]
The `@property` decorator is mostly used to "upgrade" attributes to getters/setters when things get more complicated, so the two can easily exist in parallel. Its greatest value is in limiting the number of getters/setters written in the first place!

To take an example, for the phonon DOS we can just add

```python
@property
def debye_frequency(self):
    return self.get_Debye_frequency()

@debye_frequency.setter
def debye_frequency(self, num_atoms, freq_max_fit=None)
    self.set_Debye_frequency(num_atoms, freq_max_fit=freq_max_fit)
```
and leave the existing methods intact.

For a "get-only" property like EOS volume we can use

```python
@property
def volume(self):
    return self.get_volume()

@volume.setter
def volume(self, x):
    raise Exception("Volume can't be modified; use the 'run' method.")
```

This kind of thing would help make the Python API more easily "explorable". Hours of fun can be had with an IPython shell and the ASE Atoms object, which presents this kind of interface. 😄 

I see a lot of methods in Phonopy seem to be "get-only" or "set-only", so the setters/getters style does make some sense. There are also properties like `Dos.sigma` where only a setter is provided and the value is kept in a private attribute. I don't see why this shouldn't be a public attribute?

As noted in the mailing list, the getters/setters could be phased out at a later time if there is a push to clean up the codebase by moving them inside the decorators. Personally, I do have scripts that would be broken by such a change but it would be trivial to update them. A transition period in which getters/setters raise a warning and the logic is moved into the @property blocks would be a polite way of managing this.

[NB these code examples are untested, and just sketched out based on documentation. Please don't use them directly!]

**Comment by ExpHP** [comment]
```python
@debye_frequency.setter
def debye_frequency(self, num_atoms, freq_max_fit=None)
    self.set_Debye_frequency(num_atoms, freq_max_fit=freq_max_fit)
```
You have highlighted the perfect example of when *not to use* a property.  *Somebody using this propery is unable to supply the `freq_max_fit` parameter!*

My strongly held conviction is that `@property` works well only for *very simple* properties.  Things that seem like they could be a plain data member on an object, but aren't due to implementation details (such as e.g. "it's actually stored as self.some_list[0]").  Anything more than that, and you are limiting your API.

**Comment by atztogo** [comment]
Thanks @bocklund, @jochym, @ajjackson, and @ExpHP for your valuable comments. Phonopy is written in python, so it should be written pythonic. @ajjackson, I just avoided to use public variables. It's not a good idea. Your comment motivated me to learn about python more.

**Comment by ExpHP** [comment]
Since this is still open, I'd like to take another opportunity to share just how much I **dislike properties** in Python.

One very common practice is to have a `@property` return a copy of a mutable object such as a list or numpy array.  This is to provide protection against unexpected data modification while still letting the user write `x.thing` instead of `x.thing()` or `x.get_thing()`.  Sounds good, right?

Nobody using your class can even tell the difference, right?

Well... actually, *they can.*  **Properties like this are a breeding ground for bugs in user code.**  If the user tries to modify the object, no error will be thrown... however, in actuality, nothing will happen.  Oops!

```python
>>> from pymatgen.io.vasp import Poscar
>>> p = Poscar.from_file('POSCAR')
>>> # NOTE: frac_coords is a @property
>>> p.structure.frac_coords[4]
array([ 0.10989011,  0.24175824,  0.2982931 ])
>>> # let's translate this atom...
... p.structure.frac_coords[4] += [0.2, 0, 0]
>>> p.structure.frac_coords[4]
array([ 0.10989011,  0.24175824,  0.2982931 ])
>>> # ...or not.
```

The reason Python has this issue while many other languages don't is because everything is mutable by default in Python.  In theory, you could prevent these bugs by always returning `tuple`s instead of `list`s, and always calling `a.flags.writeable = False` on arrays.  If `pymatgen` did this, then my example code would produce an error on `p.structure.frac_coords[4] += [0.2, 0, 0]` as it should.

But in general, it's difficult to turn an arbitrarily-nested Python object into something immutable.

**Comment by jochym** [comment]
There is also one more argument: explicit is better then implicit... and properties are not explicit.

**Comment by bocklund** [comment]
I agree that properties make it impossible to distinguish whether the thing you are getting back mutates the object. @jochym raises a good point as well.

It's my opinion, and I believe the intention of properties to have mutability. pymatgen has made choices to make most properties explicitly immutable and others implicit (as here). Another even more simple example than the one you provided, @ExpHP, is that if you have a `Structure`, `structure.volume = my_new_volume` doesn't work and instead you have to go through `scale_volume`. 

(Again inserting my opinion) Python lets you patch and change objects whichever way you want everywhere else. Restricting mutability with properties is as un-Pythonic as `get_` and `set_` methods in the first place.

I have not invested time into making these changes since opening this issue and I'm ok with closing this since it seems like not the direction we want to go.

**Comment by ExpHP** [comment]
@bocklund `volume` is a much more innocent example since the user at least gets an error message telling them that it didn't work.  (unlike with `frac_coords` where the user might falsely believe that it *did* work!)

I don't think 

---

> (Again inserting my opinion) Python lets you patch and change objects whichever way you want everywhere else. Restricting mutability with properties is as un-Pythonic as get_ and set_ methods in the first place.

IMO, even in python, immutability is still useful (even if only enforced by the honor priniciple).  The purpose of restricting mutability is to protect invariants.  For instance, you can rest assured that for any python dict `d`, `len(d.keys()) == len(d.values())`.

You are right that python is big on letting users mess around with internal data, but generally speaking it should at least be clear to a user when they're doing something potentially dangerous (e.g. messing with data that some other cached data depends on).  Hence the common pattern of `self._variable`, `@property def variable(self):`

**Comment by ajjackson** [comment]
To summarise, then: 

- Immutability is useful. 
- Immutable properties are less useful.
- Immutable properties which don't raise errors are dangerous.

These seem like good design principles to keep in mind!

**Comment by atztogo** [comment]
Now I believe I don't have enough ability to design API, to write the good documentation, and to manage releases defining version numbers. But I feel it is important to make the API of phonopy better for the next era of automation that needs APIs if researchers will continue to use phonopy for the next years. In fact, spglib and phono3py as well.

Do you think it is possible to implement another default phonopy's API by users' community to let the current one be legacy? Below API, I will keep maintaining the features though the design of those classes can be dirty.

**Comment by jochym** [comment]
That is actually pretty common approach to APIs. Unfortunately it is also fairy expensive for the original developers (i.e. you) since you need to maintain two interfaces instead of one. Sometimes it is better to just switch the api first (if the design decisions were bad) without changing the functionality and then "lure" the users to new version by the new functionality later, and try to provide some, not too painful, migration path. Users will adapt if you give them a good reason. I had the same problem with my elastic package - where my initial idea for an API was simply wrong.

**Comment by ExpHP** [comment]
I will point out that sometimes it can be difficult to build a good API on top of a bad one, depending on the reasons why it is bad.  The biggest issues tend to occur around global state, and around mutability (i.e. when a method changes the data contained on an object), because it's easy for bugs to be introduced into the wrapper API when the underlying implementation is updated.

I myself don't ever really use the Python API of phonopy much, so I could be wrong; but from what I've seen, it seems to me that decent-sized parts of Phonopy follow an object-oriented design that involves some mutability.  So this has me a bit concerned.

**Comment by atztogo** [comment]
Thanks @jochym and @ExpHP for experts' advices. I know there are many bad points of the current APIs. It works, but not intuitive at all. So I will go the direction to rewrite API and replace the current one at version number.

On mutability, @ExpHP is correct. But I don't know how I can take care of this right now in python.

I think I need a strong motivation for some specific purpose and the purpose will be important to decide how it would be used with, e.g., machine learning.

**Comment by atztogo** [comment]
Long time no discussion, so I am going to close this issue.

I never thought phonopy is used so much like now and it seems phonopy can be used in the next 10 years unless no good alternative appears. I think it would be good for our community to start a project to replace phonopy so that the phonon code can be maintained easily by a community, for which I can help if I can be useful. Or at least phonopy should be updated with a modern python feature because we are soon able to forget about python2.7.

Anyway thanks to you for many comments.
