### ISSUE TITLE
Bug in dynmat2fc function

### ISSUE THREAD

**Issue by abelcarreras** [atztogo/phonopy#63]
Hi Togo,

I found that recently a bug has been introduced in the dynmat2fc function. The dimension of the array containing the force constants obtained by this function are wrong.
Ex: in silicon with a supercell of 2x2x2 the dimensions of FC should be: (64, 64, 3, 3) but I obtain  (2, 64, 3, 3) instead.
I checked different versions on phonopy available in PyPI and it seems that this bug is introduced between versions 1.12.6.26 and 1.12.6.32.

**Comment by atztogo** [comment]
It's not a bug and this is not yet used for phonopy.

Because of translational invariance, fc of (2, 64, 3, 3) contains equivalent information to fc of (64, 64, 3, 3). So to save storage space for really big fc matrix, I made it so. This is also related to the change in Jan-31-2018 and Jan-7-2018 (https://atztogo.github.io/phonopy/changelog.html).
If you need full size fc like (64, 64, 3, 3) I will make an option to return it but not in (2, 64, 3, 3).

**Comment by abelcarreras** [comment]
I see, then you mean that at this time phonon.produce_force_constants() generates full size force constants but dynmat2fc generates compact format fc, right?
The point is that I wrote several unittests for dynaphopy to compare the harmonic fc and the renormalized fc, so I need both in same size. I am considering in 2 options:

1) If you plan to implement the compact fc format in phonopy as default in the future I don't need 
full size fc option in dynmat2fc. I will just stick with <1.12.6.26 for now and wait. Then I will work with compact fc format files.

2) If you plan to keep full size fc format for phonopy as default then I would like to request to make the full fc option in dynmat2fc.

thank you,

**Comment by atztogo** [comment]
`produce_force_constants` has an option to make compact fc: `produce_force_constants(calculate_full_force_constants=False)`.

I made an option `is_full_fc` for `DynmatToForceConstants`
```
class DynmatToForceConstants(object):
    def __init__(self,
                 primitive,
                 supercell,
                 frequencies=None,
                 eigenvectors=None,
                 is_full_fc=True,
                 symprec=1e-5):
```

I don't test this carefully, so it's still in develop branch.

**Comment by abelcarreras** [comment]
Ok, thank you very much.
With this I can manage by myself.

**Comment by atztogo** [comment]
I can't understand your question.

**Comment by jxli15s** [comment]
Thanks for your reply. I am sorry that I didn't describe my question clearly.
I use DFPT method of vasp to get the vasprun.xml file and then I use phonopy to generate the FORCE_CONSTANTS(FC) file by the command 'phonopy --fc vasprun.xml'. The format of FC is (n_satom, nsatom, 3, 3). I want to know how to get the FC file of compact format (n_patom, n_satom, 3, 3). 
Because I did some calculations of topological phonons and the compact format FC will simplify the process.

**Comment by atztogo** [comment]
If you have the mapping table from indices of atoms in a primitive cell to those in the supercell, you can just slice them, i.e., `fc[p2s_map]`. In phonopy, `p2s_map` is obtained by `ph.primitive.p2s_map` where `ph` is the instance of the `Phonopy` class. You can also read this documentation,
https://phonopy.github.io/phonopy/phonopy-module.html#phonopy-module

**Comment by jxli15s** [comment]
Thanks for your help. The Phonopy API is really helpful!
