### ISSUE TITLE
Possible bug in set_tensor_symmetry_PJ

### ISSUE THREAD

**Issue by sciferr** [atztogo/phonopy#67]
Hi!

In a project using phonopy we encountered some strange behaviour when using phonopy --fc-spg-symmetry command line option.

The problem might be in the function `set_tensor_symmetry_PJ` in the file `phonopy/harmonic/force_constants.py` 
```
cart_rot = np.array([similarity_transformation(lattice, rot).T
                     for rot in rotations])
cart_rot_inv = np.array([np.linalg.inv(rot) for rot in cart_rot])
```
and the similarity transform does 
```
def similarity_transformation(rot, mat):
    """ R x M x R^-1 """
return np.dot(rot, np.dot(mat, np.linalg.inv(rot)))
```
so what will be returned is (lattice=L, rot(scaled)=R_s, rot(cartesian)=R_c)

R_c=(L R_s L^-1)^T = L^-T R_s^T L^T

but I think the correct transformation is (assuming the usual convention of having cell vectors as rows)

R_c=L^T R_s L^-T

If that is the case then the function should be
```
cart_rot = np.array([similarity_transformation(lattice.T, rot)
                     for rot in rotations])
```

Notice also that R^T = R^-1 if R is orthonormal (which it should be if it is a rotation matrix?) so instead the second line can be written as
```
cart_rot_inv = np.array([rot.T for rot in cart_rot])
```
to save some numeric precission / time

Sorry for my ignorance.

Sincerely Fredrik Eriksson

**Comment by atztogo** [comment]
In this method, basis vectors are put as column vectors in L, see https://github.com/atztogo/phonopy/blob/fb26ba77b8eb06d769c97fb8940075a82b23ee11/phonopy/api_phonopy.py#L405
So I guess the current code is correct for the transformation of R. In crystallography, column vectors are more usual, so I often write basis vectors in this way. But `set_tensor_symmetry_PJ` was written by @jochym , and the code is written densely by numpy, so I don't check carefully more than this now. If you meet some weird behaviour, could you try to use `set_tensor_symmetry` instead of `set_tensor_symmetry_PJ` to compare the results? `set_tensor_symmetry` is written by me and the code is written straightforwardly though it is much slower.

If people want to use this method intensively, I should rewrite this method using python C-API for the maintainability and to make it even faster. However the force constants symmetrization may be done outside phonopy relying on any other specialized package in the future since the phonopy's symmetrization can not be done for translational symmetry simultaneously done along with space group symmetry.

**Comment by atztogo** [comment]
Can I close this issue?

**Comment by atztogo** [comment]
I will close this issue. You can reopen this if you need.
