### ISSUE TITLE
--cutoff-radius raises IndexError

### ISSUE THREAD

**Issue by zerothi** [atztogo/phonopy#74]
When using cutoff-radius option to cutoff the force constant matrix `phonopy` issues an indexerror, i.e. it tries to access a non-existing element.

I run this command:
```bash
phonopy --siesta --cutoff-radius 10. -ps band.conf
```

I tried to debug this, to no avail.

PS. I am using the latest commit, and if you want a small test example, let me know.

**Comment by atztogo** [comment]
Thanks. I will fix it. If you calculate from ``FORCE_SETS``, then with ``--full-fc`` option will pass this issue. ``--cutoff-radius`` is useful? At least no benefit for reducing computational demand.

**Comment by zerothi** [comment]
Thanks, this works!

For some of my test calculations with Siesta I can at least see that the cutoff-radius may help.

**Comment by atztogo** [comment]
I see, interesting. Phonopy's symmetrization of force constants is not strict. For VASP, usually it's enough. But I'm not sure for the other codes since PW code has advantage on the force accuracy. In case to impose more strict symmetry, I recommend to use ALM in ALAMODE code. I am preparing a script (or option) to calculation force constants for phonopy using ALM, but not yet released.

I fixed ``--cutoff-radius`` and now it works without ``--full-fc`` (``develop`` branch).

**Comment by zerothi** [comment]
Ok, great. In fact I am comparing with Inelastica against the phonon spectrum.

And it seems in siesta that it is important to do 2 things:

1) Subtract the 0-displacement forces to remove *intrinsic forces*.
2) The forces on the displaced atom are typically more inaccurate due to basis-changes. In this case it typically improves the accuracy if one uses Newtons 3rd law. I.e. by correcting the on-site forces: `F(xyz, ia) = F(xyz, ia) - SUM(F(xyz, :))`.

**Comment by atztogo** [comment]
(1) can be done ``--fz`` option, https://atztogo.github.io/phonopy/command-options.html#fz. But I hope this is not necessary in usual cases because using phonopy by default, force constants are computed by central difference. But if the basis depends on atomic position (like a big egg box effect), it may be better to subtract the residual forces. Or maybe good to use with ``--pm`` option (https://atztogo.github.io/phonopy/setting-tags.html#pm) and ``DIAG=.FALSE.`` (I now found this no corresponding command option.)

I think (2) is done in siesta-interface (I assume sum is divided by number of supercell atoms, ``F(xyz, ia) = F(xyz, ia) - SUM(F(xyz, :)/N)``. (2) is theoretically equivalent to imposing translational invariance to force constants. But maybe better to impose ``F(xyz, ia) = F(xyz, ia) - SUM(F(xyz, :))`` before force constants calculation.

**Comment by atztogo** [comment]
Oh, I found there is ``--nodiag`` for ``DIAG=.FALSE.``. I seems young me had done a good job.

**Comment by zerothi** [comment]
1. Great, I will try this, FYI, I tried doing everything without symmetry operations, I have however not tried the diag option.

2. No, I think you misinterpret. `ia` is _only_ the displaced atom. I.e. it isn't the translational invariance term. At least it isn't the corresponding `drift_force`. It is because the force evaluation of the displaced atom is "more wrong" than the other atoms.

**Comment by atztogo** [comment]
2. I see. I was incorrect. But in ideal case,
``SUM(F(xyz, :)) = 0`` so ``F(xyz, ia) = -SUM(F(xyz, all but ia))``. With numerical error, ``SUM(F(xyz, :)) = epsilon(xyz)`` that I call drift force. To remove this drift force, we have many choices, but simplest ones are such as ``F(xyz, ia) = -SUM(F(xyz, all but ia))`` or ``F(xyz, :) <- F(xyz, :) - epsilon(xyz)/N``.

If we consider displacement is infinitesimal, which is our assumption to compute harmonic force constants, to remove drift force can be equivalent to imposing translational invariance condition to the force constants.

**Comment by zerothi** [comment]
Ok, yes. I see. Perhaps this is just a problem with LCAO basis sets. Thanks for all your help.

**Comment by atztogo** [comment]
I released this fix along with master branch. Can I close this issue?

**Comment by zerothi** [comment]
Yes, thanks!

--

Kind regards Nick Papior
