### ISSUE TITLE
Some questions about POSCAR of phonopy

### ISSUE THREAD

**Issue by duxiaoxian** [atztogo/phonopy#89]
The POSCAR of Si that I imported from https://materialsproject.org/ library has 8 atoms, but there are 2 atoms in the example. Can I use this POSCAR as POSCAR-unitcell for calculation? This two kinds of  POSCARS  are used to calculate and results indicate similar curves but different ordinate scales. WHY? How can I fix my thermodynamic results without changing POSCAR?
![image](https://user-images.githubusercontent.com/45069457/53624315-d3299c00-3c3a-11e9-8bd6-cba0ceb279a8.png)

Another problem is that when I expanded the cell, I used POSCAR-00x or SPOSCAR as POSCAR for vasp calculation. After that, whether POSCAR-unitcell was used as POSCAR when running "phonopy -t -p mesh.conf" to get the thermodynamic properties.

**Comment by bocklund** [comment]
Yes, you can use the 8 atom conventional Si cell or the two atom primitive cell. The quantities calculated in phonopy are calculated "per mole-formula". That is, the quantities are *not*  divided by the number of atoms in the system. The right figure was generated with 8 atoms instead of 2, so all the quantities are 4 times as large. 

I don't understand what you are asking in your last question.

**Comment by atztogo** [comment]
I this @bocklund answered well. So I close this issue.
